name: Administracion de escuela

on:
  push:
jobs:
  integracion_continua_Equipo_4:
    runs-on: ubuntu-latest
    steps:
      - name: obtener los últimos cambios del respositorio
        uses: actions/checkout@v4
      - name: installation Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Configuración de Gradle
        uses: gradle/gradle-build-action@v2

      - name: Configuración de la base de datos H2 en memoria
        run:
            echo "spring.profiles.active=test" >> application.yml
            echo "spring.datasource.url=jdbc:h2:mem:testdb" >> application.yml
            echo "spring.datasource.driverClassName=org.h2.Driver" >> application.yml
            echo "spring.datasource.username=sa" >> application.yml
            echo "spring.datasource.password=" >> application.yml
            echo "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect" >> application.yml

      - name: Compilar el proyecto
        run: gradle build

